### ISSUE TITLE
Unable to open Geneworks reports from Moka

### ISSUE THREAD

**Issue by ClaRomano** [woook/moka-fe#424]
Through the 'Patient details' page was possible to click on 'Reports in Geneworks' and open the report from 'Long binary data'  (in 'Report **' column). Now, once clicked on 'Long binary data', a message pops up saying: 'Execution of this application has stopped due to a run-time error. The application can't continue and will be shut down'. Clicking 'ok' on this message, Moka close down.

**Comment by andyb3** [comment]
Hopefully this is now fixed. Please restart Moka and try again.

**Comment by woook** [comment]
Rolling back didn't fix it.

However, changing the location of where the word document is saved seems to work.

**Comment by woook** [comment]
@ClaRomano - please create a folder called `Temp` in your C drive. This is a workaround until we roll out a fix.
